---
- hosts: postal
  # connection: local
  vars:
    ansible_user: root
    remote_user: root

    net_interfaces:
      - name: eth0:0
        ip4: '54.38.209.145'
        netmask: '255.255.255.255'
        gw4: '54.38.209.145'
      - name: eth0:1
        ip4: '54.38.209.146'
        netmask: '255.255.255.255'
        gw4: '54.38.209.146'

    mysql_root_password: 'My $3cr3t password'

    # /etc/hosts Configuration
    etc_hosts_add_all_hosts: true
    etc_hosts_pri_dns_name: 'example.com'


    # Postal Configuration
    postal_hostname: 'example.com'
    postal_mysql_password: 'p0stalpassw0rd'


    enabled_roles:


  handlers:
    - include: handlers/main.yml

  roles:
    - role: './roles/pre'
      when: enabled_roles.pre == true

    - role: geerlingguy.ruby
      when: enabled_roles.ruby == true

    - role: geerlingguy.nodejs
      when: enabled_roles.nodejs == true

    - role: geerlingguy.git
      when: enabled_roles.git == true

    - role: mjanser.mysql
      when: enabled_roles.mysql == true

    - role: mrlesmithjr.etc-hosts
      when: enabled_roles.etcHosts == true

    - role: './roles/geerlingguy.rabbitmq' # Patch package geerlingguy.rabbitmq
      when: enabled_roles.rabbitmq == true

    - role: './roles/postal'
      when: enabled_roles.postal == true

    - role: geerlingguy.certbot
      when: enabled_roles.certbot == true

    - role: geerlingguy.nginx
      when: enabled_roles.nginx == true

    - role: './roles/post'
      when: enabled_roles.post == true
