---
- hosts: postal
  # connection: local
  vars:
    ansible_user: root
    remote_user: root

    net_interfaces:
      - name: eth0:0
        ip4: '54.38.209.145'
        netmask: '255.255.255.255'
        gw4: '54.38.209.145'
      - name: eth0:1
        ip4: '54.38.209.146'
        netmask: '255.255.255.255'
        gw4: '54.38.209.146'

    mysql_root_password: 'My $3cr3t password'

    # /etc/hosts Configuration
    etc_hosts_add_all_hosts: true
    etc_hosts_pri_dns_name: 'example.com'


    # Postal Configuration
    postal_hostname: 'example.com'
    postal_mysql_password: 'p0stalpassw0rd'


    # Enabled roles
    role_pre_enabled: false
    role_ruby_enabled: false
    role_nodejs_enabled: false
    role_git_enabled: false
    role_mysql_enabled: false
    role_etcHosts_enabled: false
    role_rabbitmq_enabled: false
    role_postal_enabled: false
    role_certbot_enabled: false
    role_nginx_enabled: false
    role_post_enabled: false


  handlers:
    - include: handlers/main.yml

  roles:
    - role: './roles/pre'
      when: role_pre_enabled == true

    - role: geerlingguy.ruby
      when: role_ruby_enabled == true

    - role: geerlingguy.nodejs
      when: role_nodejs_enabled == true

    - role: geerlingguy.git
      when: role_git_enabled == true

    - role: mjanser.mysql
      when: role_mysql_enabled == true

    - role: mrlesmithjr.etc-hosts
      when: role_etcHosts_enabled == true

    - role: './roles/geerlingguy.rabbitmq' # Patch package geerlingguy.rabbitmq
      when: role_rabbitmq_enabled == true

    - role: './roles/postal'
      when: role_postal_enabled == true

    - role: geerlingguy.certbot
      when: role_certbot_enabled == true

    - role: geerlingguy.nginx
      when: role_nginx_enabled == true

    - role: './roles/post'
      when: role_post_enabled == true
