---
- name: Add packagecloud GPG key.
  rpm_key:
    key: "https://packagecloud.io/gpg.key"
    state: present

- name: Ensure to remove any previously installed Erlang.
  yum:
    name: "erlang*"
    state: "absent"
  when: erlang_install_from_rabbitmq == true

- name: Download Erlang package.
  get_url:
    url: "{{ rabbitmq_erlang_rpm_url }}"
    dest: "/tmp/{{ rabbitmq_erlang_rpm }}"
  when: erlang_install_from_rabbitmq == true

- name: Ensure Erlang is installed.
  yum:
    name: "/tmp/{{ rabbitmq_erlang_rpm }}"
    state: "present"
  when: erlang_install_from_rabbitmq == true

- name: Ensure erlang is installed.
  package:
    name: erlang
    state: present
  when: erlang_install_from_rabbitmq == true

- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_rpm_url }}"
    dest: "/tmp/{{ rabbitmq_rpm }}"

- name: Ensure RabbitMQ is installed.
  yum:
    name: "/tmp/{{ rabbitmq_rpm }}"
    state: "present"
