---    

ansible_user: root
remote_user: root

# Network interfaces
net_interfaces:

# Ruby Configuration
ruby_install_from_source: true
ruby_download_url: https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.7.tar.gz
ruby_version: 2.3.7

ruby_install_gems:
  - bundler
  - procodile


# NodeJS Configuration
nodejs_version: '8.x'


# MySQL Configuration
mysql_vendor: mariadb # mysql or mariadb
# mysql_upstream_version: ~ # MariaDB: 10.2, MySQL: 5.7

mysql_root_password: 'My $3cr3t password'


# /etc/hosts Configuration
etc_hosts_add_all_hosts: true
etc_hosts_pri_dns_name: 'example.com'


# RabbitMQ Configuration
erlang_install_from_rabbitmq: true
erlang_version: '19.3.6.8'

rabbitmq_version: '3.7.4'

# Postal Configuration
postal_hostname: 'example.com'
postal_mysql_password: 'p0stalpassw0rd'

# Certbot (for Let's Encrypt) Configuration
certbot_admin_email: hello@example.com
certbot_create_if_missing: yes
certbot_create_standalone_stop_services: []
certbot_certs:
  - domains:
    - '{{ postal_hostname }}'

# Nginx Configuration

# Enabled roles
enabled_roles: 
  pre: true
  ruby: true
  nodejs: true
  git: true
  mysql: true
  etcHosts: true
  rabbitmq: true
  postal: true
  certbot: true
  nginx: true
  pre: true




options: 
  firewalld:
    enabled: true # Disable firewalld
    open_ports: 
      - 4369/tcp
      - 25672/tcp
      - 5671-5672/tcp
      - 15672/tcp
      - 61613-61614/tcp
      - 1883/tcp
      - 8883/tcp