---

- name: Setup networking (interfaces)
  template:
    src: ./templates/ifcfg-interface
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.name }}
    owner: root
    group: root
    mode: 644
  notify: Restart Network
  with_items: '{{ net_interfaces }}'

- name: Stop and Disable service firewalld, if running
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: options.firewalld.enabled == false

- name: Start and Enable service firewalld, if disabled
  service:
    name: firewalld
    state: started
    enabled: yes
  when: options.firewalld.enabled == true

- name: Add HTTP rule to firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
  when: options.firewalld.enabled == true

- name: Add HTTPS rule to firewalld
  firewalld:
    service: https
    permanent: true
    state: enabled
  when: options.firewalld.enabled == true

- name: Open Ports in firewalld
  firewalld:
    port: '{{ item }}'
    permanent: true
    state: enabled
  with_items: '{{ options.firewalld.open_ports }}'
  notify: Restart FirewallD
  when: options.firewalld.enabled == true