---
- name: Postal - Install packages required to build ruby (RedHat).
  yum: "name={{ item }} state=present"
  with_items:
    - wget
    - nano
    - nmcli
    - mysql-devel
  when: ansible_os_family == 'RedHat'

- name: Postal - Update apt cache (Debian).
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Postal - Install packages required to build ruby (Debian).
  apt: "name={{ item }} state=present"
  with_items:
    - wget
    - nano
    - nmcli
    - libmysqlclient-dev
  when: ansible_os_family == 'Debian'


# Add IPs - Ethernet
- name: nmcli add Ethernet - conn_name only & ip4 gw4
  nmcli:
    type: ethernet
    conn_name: '{{ item.conn_name }}'
    ip4: '{{ item.ip4 }}'
    gw4: '{{ item.gw4 }}'
    state: present
  with_items:
    - '{{ nmcli_ethernet }}'


- name: Postal - Create MySQL postal databse
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: postal
    state: present
    encoding: utf8

- name: Postal - Set MySQL postal user privileges
  mysql_user:
    name: postal
    password: "{{ postal_mysql_password }}"
    priv: "postal.*:ALL/postal-%.*:ALL PRIVILEGES" # "postal.*:ALL/postal-%.*:ALL PRIVILEGES,GRANT
    state: present


- name: Postal - Setup Postal RabbitMQ
  shell: |
    /usr/sbin/rabbitmqctl add_vhost /postal &&
    /usr/sbin/rabbitmqctl add_user postal "{{ postal_mysql_password }}" &&
    /usr/sbin/rabbitmqctl set_permissions -p /postal postal ".*" ".*" ".*"
  args:
    executable: /usr/sbin/rabbitmqctl
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
- debug: var=command_result.stdout_lines

- name: Postal - Setup Postal RabbitMQ
  shell: |
    useradd -r -m -d /opt/postal -s /bin/bash postal
    setcap 'cap_net_bind_service=+ep' $(which ruby) # /usr/local/bin/ruby
  args:
    executable: /bin/bash
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
- debug: var=command_result.stdout_lines

- name: Postal - Application Setup
  shell: |
    sudo -i -u postal mkdir -p /opt/postal/app
    wget https://postal.atech.media/packages/stable/latest.tgz -O - | sudo -u postal tar zxpv -C /opt/postal/app
    ln -s /opt/postal/app/bin/postal /usr/bin/postal
    postal bundle /opt/postal/vendor/bundle
    postal initialize-config
    postal initialize
    postal start
  args:
    executable: /bin/bash
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
- debug: var=command_result.stdout_lines

- name: Postal - Generate ssl_dhparam for Nginx
  shell: openssl dhparam -dsaparam 4096 -out /etc/ssl/dhparam.pem
  args:
    executable: /bin/bash
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
- debug: var=command_result.stdout_lines